name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Debug:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      shell: bash  
      run: |
        sudo apt update -y
        sudo apt install -y git cmake libssl-dev libcurl4-openssl-dev libaio-dev libfuse-dev libgsasl7-dev libgtest-dev libgmock-dev libgflags-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -D BUILD_TESTING=1 -D ENABLE_SASL=1 -D ENABLE_FUSE=1 -D ENABLE_URING=1 -D CMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/build -j

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        sudo ulimit -l unlimited
        ctest --timeout 3600 -V

  Release:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y git cmake libssl-dev libcurl4-openssl-dev libaio-dev libfuse-dev libgsasl7-dev libgtest-dev libgmock-dev libgflags-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -D BUILD_TESTING=1 -D ENABLE_SASL=1 -D ENABLE_FUSE=1 -D ENABLE_URING=1 -D CMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build -j

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        sudo ulimit -l unlimited
        ctest --timeout 3600 -V
